# '''
# detail:
# This is followed by training the detail model (i.e. 𝐸𝑑
# and 𝐹𝑑
# ) on VGGFace2 and VoxCeleb2 with a batch size of 6, with
# 3 images per subject, and parameters 𝜆𝑝ℎ𝑜𝐷 = 2.0, 𝜆𝑚𝑟 𝑓 = 5𝑒 − 2,
# 𝜆𝑠𝑦𝑚 = 5𝑒 − 3, 𝜆𝑑𝑐 = 1.0, and 𝜆𝑟𝑒𝑔𝐷 = 5𝑒 − 3.

# why:
# '''
# pretrained_modelpath: '/ps/scratch/yfeng/Data/Projects-data/DECA-training/training/DECA_SIGGRAPH/pretrain/model.tar'
output_dir: "Training/testGATE12_detail"
pretrained_modelpath: "Training/testGATE12/model.tar"
dataset:
  batch_size: 16
  K: 1
train:
  train_detail: True
  vis_au: False
  resume: True
  max_epochs: 10
  max_steps: 1000000
  log_steps: 250
  vis_steps: 250
  stepLR_steps: 10000
  checkpoint_steps: 1000
  lr: 0.00001
  # val_steps: 500
  # eval_steps: 1000
# dataset:
#   training_data: ['vggface2', 'vox2']
# python main_train_deca_release.py --cfg configs/release_version/deca_coarse.yml