

output_dir: "Training/testGATE6" # Emotion loss increase
pretrained_modelpath: ""

# dataset added
# AU weight change
dataset:

  batch_size: 16
  K: 1
loss:
 photo: 0.
 mainAU: 0.2
 subAU: 0.7
 weightedAU: False
 focalAU: True
 lipd: 1.2
 reg_jaw_pose: 1.0
 reg_exp: 0.00005
 lmk: 0.0
 lmk_dense: 1.2
 expression: 0.45

train:
  resume: True
  max_epochs: 10
  max_steps: 200000000
  log_steps: 500
  vis_steps: 500
  checkpoint_steps: 1000
  vis_au: True
  lr: 0.00005
#  val_steps: 500
#  eval_steps: 50000

# python main_train_deca_release.py --cfg configs/release_version/deca_coarse.yml